### ISSUE TITLE
When i open the program it goes to the bottom rigth

### ISSUE THREAD

**Issue by pachuto787** [SvenGDK/OrbisPro#1]
I am looking for Launchers for PC, i found this one, downloaded and when i open it the program goes to the bottom rigth of the screen
<img width="960" alt="image" src="https://github.com/SvenGDK/OrbisPro/assets/117043207/065d5fe4-ead2-4114-a414-d3a695837880">
I tried to move it but it doens't work, any solutions?

**Comment by SvenGDK** [comment]
This is fixed in the new 0.1 Beta.
