### ISSUE TITLE
Crashes when checks installed games

### ISSUE THREAD

**Issue by pachuto787** [SvenGDK/OrbisPro#2]
i've had an issue that the resulotion was in the rigth corner, it got fixed, hurraay!!, but when it checks the installed games, it crashes

**Comment by Artur16211** [comment]
Same, closes when searching for installed games.

**Comment by SvenGDK** [comment]
There are some missing checks that might cause the crash.
It checks directly for content in "C:\Program Files (x86)" and "C:\Games\" instead of checking if the folder even exists.

If you dont have any of those folders, try to create them manually in the "C:\" directory and start OrbisPro again.

**Comment by Amine-Kamoun** [comment]
I am having the same Issue. I do have both C:\Program Files (x86)" and "C:\Games".
Is there a log to see what is causing the crash ?

**Comment by SvenGDK** [comment]
> Amine

There are currently no logs.

- What OS are you using ? 
- Is it a Desktop/Laptop/Portable device ? 
- Are you using a firewall ?

**Comment by Amine-Kamoun** [comment]
I’m on a desktop running Windows 11 last stable build.

I’m using the default firewall of Windows

**Comment by SvenGDK** [comment]
> I’m on a desktop running Windows 11 last stable build.
> 
> I’m using the default firewall of Windows
> 
> I have two disks with some games in C:\Games and others in D:\Games. Tried renaming both folder and still the same error

[Beta v0.2 Setup Fix.zip](https://github.com/SvenGDK/OrbisPro/files/14893700/Beta.v0.2.Setup.Fix.zip)

Can you please extract this archive into the main folder of OrbisPro and replace the files.

It should now display an error with a message when checking for games. (if there is any)

**Comment by Amine-Kamoun** [comment]
Thank you for this, i have replaced the three files with the content of the zip. It still does crash but it does show any message

**Comment by SvenGDK** [comment]
> Thank you for this, i have replaced the three files with the content of the zip. It still does crash but it does **Not** show any message

Try again with these files from the archive :
[OrbisPro v0.2 TestFiles.zip](https://github.com/SvenGDK/OrbisPro/files/14896857/OrbisPro.v0.2.TestFiles.zip)

There should be now a message popping up when checking for games. Can you please show me a screenshot of this message.

**Comment by Amine-Kamoun** [comment]
I've erased the three files with the content of the new zip. Now it requires an update (maybe an update was pushed ?) and the update was done successufully then when searching for the game it freezes on the selection screen (screenshot attached).

I tried to block the app with the firewall to not let it update and use the TestFiles but now it crashes at the "Please wait" with no error message. I guess that it doesn't like not having access to the internet.
![OrbisError](https://github.com/SvenGDK/OrbisPro/assets/24244968/5e67e5a1-9d7c-419f-9f80-4a4caaf6fe06)

**Comment by SvenGDK** [comment]
A new fix is available since some minutes, let it install the new update, that's almost the only thing requiring internet.
If there is nothing shown then there are no WINDOWS games found unfortunately.
You can simply continue with X.

**Comment by SvenGDK** [comment]
> I've erased the three files with the content of the new zip. Now it requires an update (maybe an update was pushed ?) and the update was done successufully then when searching for the game it freezes on the selection screen (screenshot attached).
> 
> I tried to block the app with the firewall to not let it update and use the TestFiles but now it crashes at the "Please wait" with no error message. I guess that it doesn't like not having access to the internet. ![OrbisError](https://private-user-images.githubusercontent.com/24244968/320282693-5e67e5a1-9d7c-419f-9f80-4a4caaf6fe06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTQ4NDIsIm5iZiI6MTcxMjQ5NDU0MiwicGF0aCI6Ii8yNDI0NDk2OC8zMjAyODI2OTMtNWU2N2U1YTEtOWQ3Yy00MTlmLTlmODAtNGE0Y2FhZjZmZTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDEyNTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MzlmZWJhMmUxNDI2MDFmNGI4ODgyNDdlMGZlOTM5Yjg1MWU2OWM1NTczYWJjMGNlMzQ3YWViMjJjZjk0ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ngy-trM_jm7azV-FSycvAx4_o03lH4rgMIeNSzTbgN0)

There is are new hotfix available since some minutes, please let it install this update to resolve your issue (this requires internet).
If there are no games shown, then it cannot find any WINDOWS games.
ROMs need to be added using the File Explorer after the Setup (there's currently also a bug preventing adding some games).

**Comment by Amine-Kamoun** [comment]
The last executable that are downloaded was created at  1:20 PM UTC Time. Is this the last one ?

Even if is not able to find games, it should not freeze at that screen right? Any button (X, etc) doesn't do any effect.

**Comment by SvenGDK** [comment]
> The last executable that are downloaded was created at 1:20 PM UTC Time. Is this the last one ?
> 
> Even if is not able to find games, it should not freeze at that screen right? Any button (X, etc) doesn't do any effect.

Sorry I missed something that prevents input if no game is selected.
Please check again for an update, this time it should work.

**Comment by Amine-Kamoun** [comment]
Indeed. Now it works and no games is detected. 
I will look into that.

Thanks!
