### ISSUE TITLE
Missing DLL (libhook.dll) + crashing

### ISSUE THREAD

**Issue by pachuto787** [SvenGDK/OrbisPro#3]
tried downloading the missing DLL, cound't find it

**Comment by SvenGDK** [comment]
The libhook library will be replaced in the next update, seems to be too unstable unfortunately.

What OS are you using by the way ?
Are you using a gamepad or keyboard only ?

**Comment by SvenGDK** [comment]
> tried downloading the missing DLL, cound't find it

Try again with the new update.

**Comment by pachuto787** [comment]
I'm using Windowes, and yes only keyboard

**Comment by SvenGDK** [comment]
> I'm using Windowes, and yes only keyboard

Try again with the new update please, it should resolve the libhook issue.
